const ecoTiles = [
    // Row 0 (but coords are now [column, row])
    { coords: [0, 0], co2Reduction: 0, title: "Blank Tile" },
    { coords: [1, 0], co2Reduction: 15, title: "Wind Turbine" },
    { coords: [2, 0], co2Reduction: 0, title: "Road" },
    { coords: [3, 0], co2Reduction: 0, title: "Road" },
    { coords: [4, 0], co2Reduction: 0, title: "Road" },
    { coords: [5, 0], co2Reduction: 0, title: "Road" },
    { coords: [6, 0], co2Reduction: 10, title: "Road with Plants" },
    { coords: [7, 0], co2Reduction: 0, title: "Road with Plants" },
    { coords: [8, 0], co2Reduction: 0, title: "Road" },
    { coords: [9, 0], co2Reduction: 0, title: "Road" },
    { coords: [10, 0], co2Reduction: 0, title: "Road" },
    { coords: [11, 0], co2Reduction: 0, title: "Road" },

    // Row 1
    { coords: [0, 1], co2Reduction: 0, title: "Road" },
    { coords: [1, 1], co2Reduction: 0, title: "Road" },
    { coords: [2, 1], co2Reduction: 0, title: "Road" },
    { coords: [3, 1], co2Reduction: 4, title: "Public Transport" },
    { coords: [4, 1], co2Reduction: 4, title: "Building Insulation" },
    { coords: [5, 1], co2Reduction: 1.5, title: "Biofuels" },
    { coords: [6, 1], co2Reduction: 3, title: "Cycling" },
    { coords: [7, 1], co2Reduction: 1.5, title: "Freight Modal Shift" },
    { coords: [8, 1], co2Reduction: 2, title: "Hybrid Vehicles" },
    { coords: [9, 1], co2Reduction: 2, title: "Hybrid Vehicles" },
    { coords: [10, 1], co2Reduction: 0, title: "Hybrid Vehicles" },
    { coords: [11, 1], co2Reduction: 2, title: "Hybrid Vehicles" },

    // Row 2
    { coords: [0, 2], co2Reduction: 10, title: "Afforestation" },
    { coords: [1, 2], co2Reduction: 8, title: "Avoid deforestation" },
    { coords: [2, 2], co2Reduction: 3, title: "Food waste reduction" },
    { coords: [3, 2], co2Reduction: 4, title: "Plant-based diets" },
    { coords: [4, 2], co2Reduction: 1.5, title: "District Heating" },
    { coords: [5, 2], co2Reduction: 2, title: "Recycling/materials" },
    { coords: [6, 2], co2Reduction: 1.5, title: "Cement/steel improvements" },
    { coords: [7, 2], co2Reduction: 1, title: "Biochar" },
    { coords: [8, 2], co2Reduction: 4, title: "Industrial CCS" },
    { coords: [9, 2], co2Reduction: 2.5, title: "Compact urban design" },
    { coords: [10, 2], co2Reduction: 0, title: "Street Tunnel" },
    { coords: [11, 2], co2Reduction: 0, title: "Street Tunnel" },

    // Row 3
    { coords: [0, 3], co2Reduction: 5, title: "Street Tunnel" },
    { coords: [1, 3], co2Reduction: 8, title: "Street Tunnel" },
    { coords: [2, 3], co2Reduction: 2, title: "Recycling/materials" },
    { coords: [3, 3], co2Reduction: 2, title: "Recycling/materials" },
    { coords: [4, 3], co2Reduction: 4, title: "Soil carbon sequestration" },
    { coords: [5, 3], co2Reduction: 2, title: "Landfill methane capture" },
    { coords: [6, 3], co2Reduction: 2, title: "Freight Efficiency" },
    { coords: [7, 3], co2Reduction: 5, title: "Industrial Efficiency" },
    { coords: [8, 3], co2Reduction: 3, title: "Livestock management" },
    { coords: [9, 3], co2Reduction: 2, title: "Hydrogen/electrification" },
    { coords: [10, 3], co2Reduction: 0, title: "Simple Building" },
    { coords: [11, 3], co2Reduction: 2.5, title: "Geothermal" },

    // Row 4
    { coords: [0, 4], co2Reduction: 3, title: "Plants management" },
    { coords: [1, 4], co2Reduction: 3, title: "Plants management " },
    { coords: [2, 4], co2Reduction: 1, title: "Rice methane reduction" },
    { coords: [3, 4], co2Reduction: 3, title: "Plants management " },
    { coords: [4, 4], co2Reduction: 3, title: "Plants management " },
    { coords: [5, 4], co2Reduction: 2.5, title: "Improved crop practices" },
    { coords: [6, 4], co2Reduction: 3, title: "Waste recycling " },
    { coords: [7, 4], co2Reduction: 0, title: "Simple Building" },
    { coords: [8, 4], co2Reduction: 1, title: "Wastewater treatment" },
    { coords: [9, 4], co2Reduction: 3, title: "Plants management " },
    { coords: [10, 4], co2Reduction: 2, title: "Recycling/materials" },
    { coords: [11, 4], co2Reduction: 0, title: "Plants management" },

    // Row 5
    { coords: [0, 5], co2Reduction: 0, title: "Plants management" },
    { coords: [1, 5], co2Reduction: 10, title: "Solar Power" },
    { coords: [2, 5], co2Reduction: 10, title: "Solar Power" },
    { coords: [3, 5], co2Reduction: 0, title: "Simple Building" },
    { coords: [4, 5], co2Reduction: 0, title: "Simple Building" },
    { coords: [5, 5], co2Reduction: 0, title: "Plants management" },
    { coords: [6, 5], co2Reduction: 0.5, title: "Agri-drainage improvements" },
    { coords: [7, 5], co2Reduction: 2, title: "Heat recovery & CHP" },
    { coords: [8, 5], co2Reduction: 0, title: "Simple House" },
    { coords: [9, 5], co2Reduction: 10, title: "Solar Power" },
    { coords: [10, 5], co2Reduction: 0, title: "Simple Building" },
    { coords: [11, 5], co2Reduction: 3, title: "Rooftop Solar" }
];